"""
Prediction route — credit risk analysis form and results.
"""

from flask import Blueprint, render_template, request
from modules.validator import parse_numeric_fields, validate_hard, validate_soft
from modules.predictor import predict

predict_bp = Blueprint('predict', __name__)


@predict_bp.route('/predict', methods=['GET', 'POST'])
def predict_risk():
    """
    GET:  Render the empty prediction form.
    POST: Validate → Predict → Evaluate Policy → Render results with SHAP.
    """
    result = None
    form_data = {}
    errors = []
    warnings = []

    if request.method == 'POST':
        raw_form = request.form.to_dict()
        form_data = raw_form

        # Parse numeric fields
        parsed, parse_error = parse_numeric_fields(raw_form)

        if parse_error:
            errors.append(parse_error)
        else:
            # Hard validation
            errors = validate_hard(parsed)
            # Soft validation (warnings)
            warnings = validate_soft(parsed)

            # Run prediction + SHAP
            prediction_result = predict(parsed)

            # Evaluate business policy using new Pricing Engine
            from modules.pricing.pricing_engine import evaluate_application
            policy = evaluate_application(
                parsed,
                prediction_result['probability'],
                warnings,
            )
            
            # If there are hard errors, force the primary action to REJECTED 
            # but allow counter offers to show if generated by the engine.
            if errors:
                policy['action'] = 'REJECTED'
                policy['risk_metadata']['explanation'] = "Application rejected due to critical business rule violations."

            result = {
                **prediction_result,
                'pricing': policy,
            }

    return render_template(
        'predict.html',
        result=result,
        form_data=form_data,
        errors=errors,
        warnings=warnings,
    )


@predict_bp.route('/download_report', methods=['POST'])
def download_report():
    """
    Generate and download a PDF report based on form inputs.
    """
    from flask import send_file
    from modules.pdf_generator import generate_pdf_report
    
    raw_form = request.form.to_dict()
    parsed, parse_error = parse_numeric_fields(raw_form)
    
    if parse_error:
        return "Invalid input for report generation", 400
        
    errors = validate_hard(parsed)
    warnings = validate_soft(parsed)
    prediction_result = predict(parsed)
    from modules.pricing.pricing_engine import evaluate_application
    policy = evaluate_application(
        parsed,
        prediction_result['probability'],
        warnings,
    )
    
    if errors:
        policy['action'] = 'REJECTED'
        policy['risk_metadata']['explanation'] = "Application rejected due to critical business rule violations."
        
    result = {
        **prediction_result,
        'pricing': policy,
    }
    
    import re
    cust_id = parsed.get('customer_id', 'ID').strip()
    cust_name = parsed.get('person_name', 'Applicant').strip()
    
    # Replace spaces and non-alphanumeric chars with underscores
    safe_id = re.sub(r'[^a-zA-Z0-9_-]', '_', cust_id)
    safe_name = re.sub(r'[^a-zA-Z0-9_-]', '_', cust_name)
    
    # Collapse multiple consecutive underscores
    safe_id = re.sub(r'_+', '_', safe_id).strip('_')
    safe_name = re.sub(r'_+', '_', safe_name).strip('_')
    
    filename = f"{safe_id}_{safe_name}_credit_analysis_report.pdf"
    
    pdf_buffer = generate_pdf_report(raw_form, result, warnings)
    
    return send_file(
        pdf_buffer,
        as_attachment=True,
        download_name=filename,
        mimetype='application/pdf'
    )


